name: flutter_form_builder
publish_to: none
description: This package helps in creation of forms in Flutter by removing the boilerplate code, reusing validation, react to changes, and collect final user input.
version: 9.2.1
repository: https://github.com/icosa2050/flutter_form_builder
issue_tracker: https://github.com/icosa2050/flutter_form_builder/issues
homepage: https://github.com/icosa2050
funding: 
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.18.0 <0.20.0"

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
